# Generated by Django 2.2.1 on 2019-06-24 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cateory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cateory_name', models.CharField(max_length=50, verbose_name='分类名称')),
            ],
            options={
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='GetNum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '网站访问情况',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cateory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cateory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '博文内容',
            },
        ),
    ]
